import {
  Award,
  BarChart3,
  BookOpenCheck,
  Bot,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  ChartNoAxesCombined,
  FolderCode,
  GraduationCap,
  Handshake,
  Landmark,
  Laptop,
  Presentation,
  Rocket,
  Settings2,
  ShieldCheck,
  Sprout,
  Target,
  UsersRound,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";

import type { TrainingIcon } from "@/types/training";

/** Data stores icon names as strings; this resolves them to Lucide icons. */
export const trainingIcons: Record<TrainingIcon, LucideIcon> = {
  Award,
  BarChart3,
  BookOpenCheck,
  Bot,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  ChartNoAxesCombined,
  FolderCode,
  GraduationCap,
  Handshake,
  Landmark,
  Laptop,
  Presentation,
  Rocket,
  Settings2,
  ShieldCheck,
  Sprout,
  Target,
  UsersRound,
  Workflow,
  Wrench,
};
